version: 2

sources:
#   - name: jaffle_shop
#     database: analytics
#     schema: jaffle_shop
#     freshness: 
#       warn_after: {count: 12, period: hour}
#       error_after: {count: 24, period: hour}
#     loaded_at_field: _etl_loaded_at

#     tables:
#       - name: orders
#         freshness: # make this a little more strict
#           # warn_after: {count: 6, period: hour}
#           # error_after: {count: 12, period: hour}
#       - name: customers # this inherits the default freshness defined in the jaffle_shop source block at the beginning
        

  - name: stripe
    database: analytics
    schema: stripe 
    tables:
      - name: payments
